- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"

  - name: Python Version
    command: "python3 --version 2>&1"
    register: python3    
  - debug: msg="{{ python3.stdout }}"

  - name: Ansible Version
    command: "ansible --version"
    register: ansible    
  - debug: msg="{{ ansible.stdout }}"
